// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailCentral.Api.Data;

#nullable disable

namespace RetailCentral.Api.Migrations
{
    [DbContext(typeof(RetailCentralDbContext))]
    [Migration("20260323173656_AddAuditLogs")]
    partial class AddAuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InstalledSoftware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstallDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("InstalledSoftwares");
                });

            modelBuilder.Entity("InstalledWindowsUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HotFixId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstalledOn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("InstalledWindowsUpdates");
                });

            modelBuilder.Entity("RetailCentral.Api.Data.Entities.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowOutsideWindow")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecuteMode")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("UseStoreLocalTime")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("WindowEndLocal")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("WindowStartLocal")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("Status");

                    b.ToTable("Deployments", (string)null);
                });

            modelBuilder.Entity("RetailCentral.Api.Data.Entities.DeploymentDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("DeploymentId")
                        .HasColumnType("int");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DownloadCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DownloadStartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExecuteCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecuteStartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecuteStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Status");

                    b.ToTable("DeploymentDevices", (string)null);
                });

            modelBuilder.Entity("RetailCentral.Api.Data.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExecutionArguments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExecutionCommand")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PackageType")
                        .HasColumnType("int");

                    b.Property<int>("RebootBehavior")
                        .HasColumnType("int");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("RetailCentral.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.Command", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IssuedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LockedByDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LockedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommandId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.CommandResult", b =>
                {
                    b.Property<long>("CommandResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommandResultId"));

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdErr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdOut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommandResultId");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.ToTable("CommandResults");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("LastAuthTimestampUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("LastIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DeviceId");

                    b.HasIndex("StoreNumber", "Hostname");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.DeviceGroup", b =>
                {
                    b.Property<int>("DeviceGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceGroupId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DeviceGroupId");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.ToTable("DeviceGroups");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.DeviceGroupMember", b =>
                {
                    b.Property<int>("DeviceGroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceGroupMemberId"));

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceGroupId")
                        .HasColumnType("int");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceGroupMemberId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceGroupId", "DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceGroupMembers");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.Heartbeat", b =>
                {
                    b.Property<long>("HeartbeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HeartbeatId"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("HeartbeatId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.ProcessStatusInventory", b =>
                {
                    b.Property<long>("ProcessStatusInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProcessStatusInventoryId"));

                    b.Property<decimal?>("AgentCpuPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AgentProcessCount")
                        .HasColumnType("int");

                    b.Property<string>("AgentProcessName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AgentRunning")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AgentStartedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AgentWorkingSetMb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PosCpuPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PosProcessCount")
                        .HasColumnType("int");

                    b.Property<string>("PosProcessName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PosRunning")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PosStartedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PosWorkingSetMb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RetailShellCpuPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RetailShellProcessCount")
                        .HasColumnType("int");

                    b.Property<string>("RetailShellProcessName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RetailShellRunning")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RetailShellStartedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RetailShellWorkingSetMb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ProcessStatusInventoryId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("ProcessStatusInventories");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.RegisterInventory", b =>
                {
                    b.Property<long>("RegisterInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegisterInventoryId"));

                    b.Property<string>("CPUArch")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComputerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HardDriveFreeSpace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HardDriveSize")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReboot")
                        .HasColumnType("datetime2");

                    b.Property<string>("MACAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Memory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OSVersion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegisterNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReleaseApplied")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReleaseLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScannerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScannerSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Store")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoreAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StoreCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StoreState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoreZipCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SystemBuildDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifoneIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerifoneModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegisterInventoryId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("RegisterInventories");
                });

            modelBuilder.Entity("RetailCentral.Api.Data.Entities.Deployment", b =>
                {
                    b.HasOne("RetailCentral.Api.Data.Entities.Package", "Package")
                        .WithMany("Deployments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("RetailCentral.Api.Data.Entities.DeploymentDevice", b =>
                {
                    b.HasOne("RetailCentral.Api.Data.Entities.Deployment", "Deployment")
                        .WithMany("DeploymentDevices")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.DeviceGroupMember", b =>
                {
                    b.HasOne("RetailCentral.Api.Models.DeviceGroup", "DeviceGroup")
                        .WithMany()
                        .HasForeignKey("DeviceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailCentral.Api.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("DeviceGroup");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.Heartbeat", b =>
                {
                    b.HasOne("RetailCentral.Api.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RetailCentral.Api.Models.ProcessStatusInventory", b =>
                {
                    b.HasOne("RetailCentral.Api.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RetailCentral.Api.Models.RegisterInventory", b =>
                {
                    b.HasOne("RetailCentral.Api.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RetailCentral.Api.Data.Entities.Deployment", b =>
                {
                    b.Navigation("DeploymentDevices");
                });

            modelBuilder.Entity("RetailCentral.Api.Data.Entities.Package", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
